### PR TITLE
Add u128 and i128.

### LINKED ISSUE #3: Add support for `i128` and `u128`
Should be behind a feature, so default works on stable.

### PR DESCRIPTION
**Pull request by pepyakin**
Fixes #3 

Although that doesn't require feature gates since u128 and i128 are already in stable.

### CODE REVIEW

**Comment by pepyakin** [comment]
Thanks @derekdreery , could you please release it on crates.io?

**Comment by richard-uk1** [comment]
Already on it :)

**Comment by pepyakin** [comment]
Oh, sorry, I meant the version that includes this change : )

**Comment by richard-uk1** [comment]
version 0.1.2 is out with i/u128 :)

**Comment by pepyakin** [comment]
Awesome, thank you!

**Pull request merged**
